"""001_Initial

Revision ID: a1fd7b48c40f
Revises: 
Create Date: 2022-11-07 21:48:30.100481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fd7b48c40f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=26), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['todo_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_entries')
    op.drop_table('todo_labels')
    # ### end Alembic commands ###
